# In this Dockerfile the Spring Boot JAR file is copied into the Docker image and
# then executed as the application JAR

# Start with a base image containing Java runtime
FROM openjdk:11-slim

# The application's jar file
ARG JAR_FILE

# Add the application's jar to the container
COPY ${JAR_FILE} app.jar

# Execute the application
ENTRYPOINT ["java", "-jar", "/app.jar"]
